import Head from "next/head";
import PokemonList from "../components/PokemonList";
import { Box } from "@mui/material";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Box px={20}>
          <PokemonList />
        </Box>
      </main>
    </div>
  );
}
